services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        imageVariant: 8.3-bullseye
    env_file:
      - .env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    image: mariadb:12.0.2
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev

volumes:
  db-data:
